### ISSUE TITLE
Resources for drawing pixels to canvas

### ISSUE THREAD

**Issue by Nolence** [matthew-carroll/flutter_processing#36]
I watched your recent video on bitmap and was reminded how I hit this road block some time ago too. Here are two resources that helped me out a bit back then. Hope they can be of use

https://itnext.io/procedural-textures-with-flutter-efcf546cd1fc

https://stackoverflow.com/questions/55844043/how-do-i-render-individual-pixels-in-flutter

Here is also an open PR requesting a synchronous way to draw pixels

https://github.com/flutter/flutter/issues/37180

Feel free to close

**Comment by matthew-carroll** [comment]
Hi @Nolence thanks for posting. I'm one of the thumbs up on that Flutter issue you referenced :)

As for the stackoverflow post, that's the same approach we took in the video.

I'll take a look at the blog post you linked.

I'm going to close this ticket because it's not an issue with the project. In the future, feel free to use Twitter for this purpose and tag me in your post.
