### ISSUE TITLE
Extract Sketch.simple into a class SimpleSketch

### ISSUE THREAD

**Issue by jkoenig134** [matthew-carroll/flutter_processing#69]
Hey Mattew!

This is a proposal for an idea I had for a long time while watching your videos.
I really like the Idea of Sketch.simple but it kind of feels like it is not placed correctly. If I got it right, the main usage of Sketch should be extending it. My approach to this proposal is exactly this. 

I extracted the callbacks from Sketch and the Sketch.simple constructor in a new class called SimpleSketch. The usage is literally the same as in Sketch.simple.

```dart
Processing(
  sketch: Sketch.simple(
    setup: (sketch) async {
      // TODO: do Sketch setup
    },
    draw: (sketch) async {
      // TODO: do Sketch drawing
    },
  ),
),
}
```
becomes
```dart
Processing(
  sketch: SimpleSketch(
    setup: (sketch) async {
      // TODO: do Sketch setup
    },
    draw: (sketch) async {
      // TODO: do Sketch drawing
    },
  ),
),
}
```

If you want to look over my approach, [I implemented it](https://github.com/jkoenig134/flutter_processing/tree/refactor/extract-simple-scetch-from-sketch) to see if it's clean and doable 👍🏼

**Comment by matthew-carroll** [comment]
Hi @jkoenig134 - can you explain what the benefit is of this change? It looks like it retains the same end-user experience, but adds an additional class. I think the original named constructor was a fine thing to have, so I'm not sure why we'd need to change it.

**Comment by jkoenig134** [comment]
> Hi @jkoenig134 - can you explain what the benefit is of this change? It looks like it retains the same end-user experience, but adds an additional class. I think the original named constructor was a fine thing to have, so I'm not sure why we'd need to change it.

Yes, the end-user experience is the same, but
1 - the purpose of the Sketch class get clearer
2 - it's easier to understand for maintainers.. the callback functions are kind of irritating in the Sketch class
3 - I thought it's another step to split some things in the project

**Comment by matthew-carroll** [comment]
> 1 - the purpose of the Sketch class get clearer (extending it or using a SimpleSketch thats extending it)

I wouldn't say this is true. Currently, the `Sketch` class is what you use when you want to implement a Processing sketch. I think that's pretty clear.

> 2 - it's easier to understand for maintainers.. the callback functions are kind of irritating in the Sketch class

Your proposal has the same callbacks, which will require the same maintenance. But I think your proposal will require some duplication of code. Also, users can extend `Sketch` like they do with Processing, without using the callbacks. So the callbacks are optional.

> 3 - I thought it's another step to split some things in the project

Some things should be split up, other things shouldn't. Right now, I'm not seeing the benefit of making this change.

I'm going to close this issue because I don't see a clear problem to be solved. If stronger evidence comes up later that there's a problem, then we can take another look.
