### ISSUE TITLE
Are there any plans to support air safety?

### ISSUE THREAD

**Issue by peter100u** [matthew-carroll/flutter_processing#73]
I am a flutter beginner and want to use processing more, but you this library, did not upgrade the latest dart version, I also do not have the ability to upgrade to adapt to your empty security issues, please ask you have scheduling

**Comment by matthew-carroll** [comment]
I don't know what "air safety" is. This codebase does use a recent version of Dart, but you need to reference this GitHub repo in your pubspec instead of the pub.dev version. A new pub.dev version will be available sometime soon.

If you have specific issues, please file one ticker per issue and fully define the issue that you're having. You can check the CONTRIBUTING.md guide for more details.
