### ISSUE TITLE
flutter_processing Operation effect

### ISSUE THREAD

**Issue by peter100u** [matthew-carroll/flutter_processing#93]
When I was using particle effects, I found that fluter_ Processing is too laggy, and the running efficiency is far less than processing.java or p5.js. I wonder if you have considered a further optimization or change the rendering engine, for example. https://github.com/wasabia/flutter_ gl
When I was using particle effects, I found that fluter_ Processing is too laggy, and the running efficiency is far less than processing.java or p5.js. I wonder if you have considered a further optimization or change the rendering engine, such as

**Comment by matthew-carroll** [comment]
This is the best you're going to get for the foreseeable future. I don't have any plans to change the rendering engine, because the rendering engine is Flutter. That would defeat the purpose of the project.

If you find a way to make this package work faster with Flutter then you're welcome to suggest something.

For now, this issue isn't actionable, so I'm going to close it.

**Comment by peter100u** [comment]
ok , thank you
